name: Update composer.lock

on:
  push:
    branches:
    - main

  schedule:
  - cron: '0 2 * * *'

  pull_request:

env:
  GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
  GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}

jobs:
  update-composer-lock:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT }}
    - name: Update lock file
      uses: php-actions/composer@v6
    - name: Commit changes
      run: |
        git config --global user.name "${GIT_USER_EMAIL}"
        git config --global user.email "${GIT_USER_EMAIL}"        
        git commit -am "Update composer.lock file"
        git push
